# SPDX-FileCopyrightText: 2026 KIM Hyunjae
# SPDX-License-Identifier: AGPL-3.0-or-later

[global]
flavor = "standard"
disable = [
  "first-line-heading",
  "heading-increment",
  "line-length",
  "no-emphasis-as-heading",
  "no-inline-html",
  "single-title",
]

[MD007] # ul-indent
indent = 4

[MD033] # inline HTML, centered header in README
allowed-elements = ["div"]

[MD060]
enabled = true    # table-format
style = "aligned"
